name: Bank

on:
  push:
    branches: [ master ]
    paths:
      - 'bank/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bank

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Run tests
      run: mvn test