name: Bank Spring Boot

on:
  push:
    branches: [ master ]
    paths:
      - './bankboot'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bankboot

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build Spring Boot
      run: mvn -B package --file pom.xml