name: Bank Spring Boot

on:
  push:
    branches: [ master ]
    paths:
      - 'bankboot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14

    - name: Build Spring Boot
      working-directory: ./bankboot
      run: mvn -B package --file pom.xml